// users
export const SOMETHING_DONE_TO_USER = 'SOMETHING_DONE_TO_USER';

// sessions
export const RECEIVE_SESSION = 'RECEIVE_SESSION';
export const FAIL_ADD_SESSION = 'FAIL_ADD_SESSION';
export const RECEIVE_SESSIONS = 'RECEIVE_SESSIONS';
export const FAIL_FETCH_SESSIONS = 'FAIL_ADD_SESSIONS';