// users
export const SOMETHING_DONE_TO_USER = 'SOMETHING_DONE_TO_USER';

// sessions
export const RECEIVE_SESSION = 'RECEIVE_SESSION';
export const FAIL_ADD_SESSION = 'FAIL_ADD_SESSION';
export const RECEIVE_SESSIONS = 'RECEIVE_SESSIONS';
export const FAIL_FETCH_SESSIONS = 'FAIL_ADD_SESSIONS';

// votes
export const RECEIVE_VOTE = 'RECEIVE_VOTE';
export const FAIL_SET_VOTE = 'FAIL_SET_VOTE';
export const RECEIVE_VOTES = 'RECEIVE_VOTES';
export const FAIL_FETCH_VOTES = 'FAIL_FETCH_VOTES';
export const RECEIVE_FACILITATE = 'RECEIVE_FACILITATE';
export const FAIL_SET_FACILITATE = 'FAIL_SET_FACILITATE';
export const RECEIVE_FACILITATES = 'RECEIVE_FACILITATES';
export const FAIL_FETCH_FACILITATES = 'FAIL_FETCH_FACILITATES';