// users
export const RECEIVE_USERS = 'RECEIVE_USERS';
export const FAIL_FETCH_USERS = 'FAIL_FETCH_USERS';
export const LOGIN = 'LOGIN';
export const START_LOGIN = 'START_LOGIN';
export const FAIL_LOGIN = 'FAIL_LOGIN';
export const LOGOUT = 'LOGOUT';

// conference
export const RECEIVE_CONFERENCES = 'RECEIVE_CONFERENCES';
export const FAIL_FETCH_CONFERENCES = 'FAIL_FETCH_CONFERENCES';
export const RECEIVE_CONFERENCE = 'RECEIVE_CONFERENCE';
export const FAIL_SET_TIMES = 'FAIL_SET_TIMES';
export const FAIL_PATCH_CONFERENCE = 'FAIL_PATCH_CONFERENCE';

// sessions
export const RECEIVE_NEW_SESSION = 'RECEIVE_NEW_SESSION';
export const FAIL_ADD_SESSION = 'FAIL_ADD_SESSION';
export const RECEIVE_SESSIONS = 'RECEIVE_SESSIONS';
export const FAIL_FETCH_SESSIONS = 'FAIL_ADD_SESSIONS';
export const START_UPDATING_SESSION = 'START_UPDATING_SESSION';
export const RECEIVE_UPDATED_SESSION = 'RECEIVE_UPDATED_SESSION';
export const FAIL_UPDATE_SESSION = 'FAIL_UPDATE_SESSION';
export const RECEIVE_DELETED_SESSION = 'RECEIVE_DELETED_SESSION';
export const FAIL_DELETE_SESSION = 'FAIL_DELETE_SESSION';
export const RECEIVE_MERGED_SESSION = 'RECEIVE_MERGED_SESSION';
export const FAIL_MERGE_SESSION = 'FAIL_MERGE_SESSION';

// votes
export const SET_VOTE = 'SET_VOTE';
export const SET_VOTE_COMPLETE = 'SET_VOTE_COMPLETE';
export const SET_VOTE_FAILED = 'SET_VOTE_FAILED';
export const RECEIVE_VOTES = 'RECEIVE_VOTES';
export const FAIL_FETCH_VOTES = 'FAIL_FETCH_VOTES';

// facilitate
export const SET_FACILITATE = 'SET_FACILITATE';
export const SET_FACILITATE_COMPLETE = 'SET_FACILITATE_COMPLETE';
export const SET_FACILITATE_FAILED = 'SET_FACILITATE_FAILED';
export const RECEIVE_FACILITATES = 'RECEIVE_FACILITATES';
export const FAIL_FETCH_FACILITATES = 'FAIL_FETCH_FACILITATES';
export const RECEIVE_FACILITATORS = 'RECEIVE_FACILITATORS';
export const FAIL_FETCH_FACILITATORS = 'FAIL_FETCH_FACILITATORS';
export const RECEIVE_FACILITATE_ADMIN = 'RECEIVE_FACILITATE_ADMIN';
export const FAIL_SET_FACILITATE_ADMIN = 'FAIL_SET_FACILITATE_ADMIN';