ALTER TABLE Slots DROP FOREIGN KEY `Slots_ibfk_3`;
ALTER TABLE Slots DROP FOREIGN KEY `Slots_ibfk_2`;
ALTER TABLE Slots DROP FOREIGN KEY `Slots_ibfk_1`;
ALTER TABLE Slots DROP PRIMARY KEY;
ALTER TABLE Slots ADD PRIMARY KEY (timeId, roomId);
ALTER TABLE Slots ADD CONSTRAINT
    FOREIGN KEY (sessionId) REFERENCES Sessions (id) ON DELETE CASCADE;
ALTER TABLE Slots ADD CONSTRAINT
    FOREIGN KEY (timeId) REFERENCES Times (id);
ALTER TABLE Slots ADD CONSTRAINT
    FOREIGN KEY (roomId) REFERENCES Rooms (id);