ALTER TABLE Slots DROP FOREIGN KEY `Slots_ibfk_3`;
ALTER TABLE Slots ADD CONSTRAINT
    FOREIGN KEY (sessionId) REFERENCES Sessions (id) ON DELETE CASCADE;

ALTER TABLE Votes DROP FOREIGN KEY `Votes_ibfk_2`;
ALTER TABLE Votes ADD CONSTRAINT
    FOREIGN KEY (sessionId) REFERENCES Sessions (id) ON DELETE CASCADE;

ALTER TABLE Facilitators DROP FOREIGN KEY `Facilitators_ibfk_2`;
ALTER TABLE Facilitators ADD CONSTRAINT
    FOREIGN KEY (sessionId) REFERENCES Sessions (id) ON DELETE CASCADE;